CREATE TABLE PELICULA (ID_PELICULA INTEGER,
                        TITULO VARCHAR2(120),
                        SINOPSIS VARCHAR2(500),
                        CLASIFICACION VARCHAR2(5),
                        CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
                        );
                        
     CREATE SEQUENCE SEC_PELICULA 
      start with 1
      increment by 1
      nomaxvalue;


CREATE OR REPLACE PROCEDURE GUARDAR_PELICULA 
(
  MY_ID_PELICULA OUT NUMBER  
, MY_TITULO IN VARCHAR2  
, MY_SINOPSIS IN VARCHAR2  
, MY_CLASIFICACION IN VARCHAR2  
) AS 
BEGIN
  SELECT SEC_PELICULA.NEXTVAL INTO MY_ID_PELICULA FROM DUAL;
  INSERT INTO PELICULA VALUES(MY_ID_PELICULA,MY_TITULO,MY_SINOPSIS,MY_CLASIFICACION);
END GUARDAR_PELICULA;
/


DECLARE
VALOR INTEGER;
BEGIN
GUARDAR_PELICULA(VALOR,'EL RENACIDO','ESTA MAS O MENOS','B15');
END;
/

SELECT * FROM PELICULA;
