CREATE TABLE CLIENTE (ID_CLIENTE INTEGER,
NOMBRE VARCHAR2(30),
SUELDO_BASE FLOAT, 
EMAIL VARCHAR2(30), 
CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE));

CREATE TABLE DIRECCION (ID_DIRECCION INTEGER,
ID_CLIENTE INTEGER,
CALLE VARCHAR2(30),
NUMERO_BASE INTEGER, 
CP INTEGER, 
MUNICIPIO VARCHAR2(30),

CREATE TABLE SIMPLE1 (ID_SIMPLE INTEGER, EDAD INTEGER, NOMBRE VARCHAR2(40));
--lA LLENAMOS CON INFORMACION RAPIDA
DECLARE
MI INTEGER;
BEGIN
MI:=20;
FOR i IN 1..20 LOOP
MI:=MI+i;
INSERT INTO SIMPLE1 VALUES (i,MI, 'MARCELO');
END LOOP;
END;
/
--HACER UN SELECT
SELECT * FROM SIMPLE1;

UPDATE SIMPLE1 SET NOMBRE='XXX' WHERE EDAD=21;
SET SERVEROUTPUT ON;

DECLARE
MI_NOMBRE VARCHAR(40);
BEGIN 
SELECT NOMBRE INTO MI_NOMBRE FROM SIMPLE1 WHERE EDAD=21;
DBMS_OUTPUT.PUT_LINE(MI_NOMBRE);
END;
/
DELETE FROM SIMPLE1;
INSERT INTO SIMPLE1 VALUES(1,21,'MARCELO');
INSERT INTO SIMPLE1 VALUES(2,23,'MAURICIO');
INSERT INTO SIMPLE1 VALUES(3,23,'jONAS');


DECLARE 
MI_NOMBRE VARCHAR(40);
BEGIN
SELECT NOMBRE INTO MI_NOMBRE FROM SIMPLE1;
DBMS_OUTPUT.PUT_LINE(MI_NOMBRE);
END;
/
